name: player
description: Audio-visual mesh gradient player
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mesh_gradient: ^1.3.8
  file_picker: ^6.1.1
  flutter_media_metadata: ^1.0.0+1
  palette_generator: ^0.3.3
  path_provider: ^2.1.5
  just_audio: 0.9.33
  audio_waveforms: 1.3.0
  just_waveform: ^0.0.7
  flutter_audio_waveforms: ^1.1.2
  audioplayers: ^6.4.0
  image: ^4.5.4
  window_manager: ^0.5.0
  shared_preferences: ^2.5.3
  
  




flutter:
  uses-material-design: true  